<?php

namespace AppBundle\Repository;

/**
 * DepositoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositoRepository extends \Doctrine\ORM\EntityRepository
{
}
