<?php

namespace AppBundle\Repository;

/**
 * DesvioPartidasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesvioPartidasRepository extends \Doctrine\ORM\EntityRepository
{
}
