<?php

namespace AppBundle\Repository;

/**
 * PartidasCobolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidasCobolRepository extends \Doctrine\ORM\EntityRepository
{
}
