<?php

namespace AppBundle\Repository;

/**
 * PartidasMovRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidasMovRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastNroMov($codDesvio, $nroPartida){
        $qb = $this
            ->createQueryBuilder('p')
            ->select('MAX(p.nroMov)')
            ->where('p.codDesvio = '. $codDesvio)
            ->andWhere('p.nroPartida = '. $nroPartida);
            
        return $qb->getQuery()->getSingleResult();
            
    }
}
