<?php

namespace AppBundle\Repository;

/**
 * PartidasMovRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidasMovRepository extends \Doctrine\ORM\EntityRepository
{
}
