<?php

namespace AppBundle\Repository;

/**
 * ScrneoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScrneoRepository extends \Doctrine\ORM\EntityRepository
{
}
