<?php

namespace AppBundle\Repository;

/**
 * TipoMovPartidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMovPartidaRepository extends \Doctrine\ORM\EntityRepository
{
}
