<?php

namespace AppBundle\Repository;

/**
 * TrabajoCaracteristicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajoCaracteristicaRepository extends \Doctrine\ORM\EntityRepository
{
}
